### ISSUE TITLE
Fix break in server

### ISSUE THREAD

**Issue by zenglenn42** [greenleavesbyroot/greenleaves#78]
admins-MacBook-Pro:greenleaves a$ nodemon --ignore 'client/*'
[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
ENV = undefined
Executing (default): CREATE TABLE IF NOT EXISTS `orderProducts` (`id` INTEGER NOT NULL auto_increment , `order_id` INTEGER NOT NULL, `product_id` INTEGER NOT NULL, `qty_ordered` INTEGER NOT NULL, `qty_unit_id` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `orderProducts` FROM `greenleaves_db`
Executing (default): CREATE TABLE IF NOT EXISTS `Orders` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER NOT NULL, `shipped` TINYINT(1) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Orders` FROM `greenleaves_db`
Executing (default): CREATE TABLE IF NOT EXISTS `Products` (`id` INTEGER NOT NULL auto_increment , `name_en` VARCHAR(255), `name_cn` VARCHAR(255), `name_kr` VARCHAR(255), `name_vn` VARCHAR(255), `description` TEXT, `category` ENUM('roots', 'leafy', 'fruit', 'misc', 'choy'), `quantity` INTEGER, `availability` TINYINT(1), `unit_id` INTEGER, `imgsrc` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Products` FROM `greenleaves_db`
Executing (default): CREATE TABLE IF NOT EXISTS `units` (`id` INTEGER NOT NULL auto_increment , `unit_name` VARCHAR(255) NOT NULL, `unit_abbrev` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `units` FROM `greenleaves_db`
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL, `email` TEXT NOT NULL, `phone_number` INTEGER NOT NULL DEFAULT false, `billing_address` TEXT NOT NULL, `shipping_address` TEXT NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Users` FROM `greenleaves_db`
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3001
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Function.listen (/Users/a/dev/ut/git/greenleaves/node_modules/express/lib/application.js:618:24)
    at db.sequelize.sync.then (/Users/a/dev/ut/git/greenleaves/server.js:21:7)
    at tryCatcher (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/a/dev/ut/git/greenleaves/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by zenglenn42** [comment]
Interestingly when I manually seed the Users table from my uplevel scripts/userSeeds.sql with uppercase Users, all is well and the server subsequently starts without issue (i.e., in the case of an already populated Users table).
